import { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Header } from '../components/Header';
import {
  Salad,
  Flame,
  Shield,
  Loader2,
  Download,
  Leaf,
  UtensilsCrossed,
  Ban,
  Coffee,
  Sparkles,
  Heart,
} from 'lucide-react';
import { useAuth } from '../lib/auth';
import { toast } from 'sonner';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3003';

interface DietPlanData {
  mode: string;
  title: string;
  summary: string;
  eat: string[];
  avoid: string[];
  kadha_recipe: {
    name: string;
    ingredients: string[];
    method: string;
    when_to_drink: string;
  };
  meal_plan: {
    morning: string;
    breakfast: string;
    mid_morning: string;
    lunch: string;
    evening_snack: string;
    dinner: string;
    before_bed: string;
  };
  tips: string[];
}

export function DietPlan() {
  const { user } = useAuth();
  const [mode, setMode] = useState<'ill' | 'well' | null>(null);
  const [symptoms, setSymptoms] = useState('');
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<DietPlanData | null>(null);

  const generatePlan = async () => {
    if (!user || !mode) return;
    setLoading(true);

    try {
      const response = await fetch(`${API_URL}/api/diet`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ mode, symptoms, userId: user.id }),
      });

      if (response.ok) {
        const data = await response.json();
        setPlan(data);
        toast.success('Diet plan generated!');
      } else {
        toast.error('Failed to generate diet plan. Is the server running?');
      }
    } catch {
      toast.error('Cannot reach the API server.');
    }

    setLoading(false);
  };

  const handleDownloadPDF = () => {
    if (!plan) return;
    // Generate a simple text-based printable version
    const content = `
IMMUNOTRACE - PERSONALIZED DIET PLAN
=====================================
${plan.title}

${plan.summary}

WHAT TO EAT:
${plan.eat.map(e => `• ${e}`).join('\n')}

WHAT TO AVOID:
${plan.avoid.map(a => `• ${a}`).join('\n')}

KADHA RECIPE: ${plan.kadha_recipe.name}
Ingredients: ${plan.kadha_recipe.ingredients.join(', ')}
Method: ${plan.kadha_recipe.method}
When: ${plan.kadha_recipe.when_to_drink}

MEAL PLAN:
Morning: ${plan.meal_plan.morning}
Breakfast: ${plan.meal_plan.breakfast}
Mid-Morning: ${plan.meal_plan.mid_morning}
Lunch: ${plan.meal_plan.lunch}
Evening Snack: ${plan.meal_plan.evening_snack}
Dinner: ${plan.meal_plan.dinner}
Before Bed: ${plan.meal_plan.before_bed}

TIPS:
${plan.tips.map(t => `• ${t}`).join('\n')}

Generated by ImmunoTrace AI
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ImmunoTrace_Diet_Plan.txt';
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Diet plan downloaded!');
  };

  return (
    <div className="min-h-screen pt-8 pr-8 pb-12 md:pl-28">
      <Header />
      <main className="max-w-[900px] mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
        >
          <div className="mb-8">
            <h1 className="text-[32px] font-medium text-slate-800 tracking-tight mb-1">
              Personalized Diet Plan
            </h1>
            <p className="text-sm text-slate-500">
              AI-powered nutrition advice based on your medical history and current health.
            </p>
          </div>

          <AnimatePresence mode="wait">
            {!plan ? (
              <motion.div
                key="selector"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="space-y-6"
              >
                {/* Mode Selection */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <button
                    onClick={() => setMode('ill')}
                    className={`p-8 rounded-[32px] border-2 text-left transition-all ${
                      mode === 'ill'
                        ? 'border-[#E63946] bg-red-50/50 shadow-lg'
                        : 'border-white bg-white/80 hover:border-slate-200'
                    } backdrop-blur-2xl shadow-[0_8px_30px_rgb(0,0,0,0.03)]`}
                  >
                    <div className={`w-14 h-14 rounded-[20px] flex items-center justify-center mb-4 ${
                      mode === 'ill' ? 'bg-[#E63946]/10' : 'bg-slate-100'
                    }`}>
                      <Flame className={`w-7 h-7 ${mode === 'ill' ? 'text-[#E63946]' : 'text-slate-400'}`} />
                    </div>
                    <h3 className="text-lg font-medium text-slate-800 mb-2">Currently Ill</h3>
                    <p className="text-sm text-slate-500">
                      I have symptoms right now and need a healing diet plan with home remedies.
                    </p>
                  </button>

                  <button
                    onClick={() => setMode('well')}
                    className={`p-8 rounded-[32px] border-2 text-left transition-all ${
                      mode === 'well'
                        ? 'border-[#2EC4B6] bg-[#EAF7F6]/50 shadow-lg'
                        : 'border-white bg-white/80 hover:border-slate-200'
                    } backdrop-blur-2xl shadow-[0_8px_30px_rgb(0,0,0,0.03)]`}
                  >
                    <div className={`w-14 h-14 rounded-[20px] flex items-center justify-center mb-4 ${
                      mode === 'well' ? 'bg-[#2EC4B6]/10' : 'bg-slate-100'
                    }`}>
                      <Shield className={`w-7 h-7 ${mode === 'well' ? 'text-[#2EC4B6]' : 'text-slate-400'}`} />
                    </div>
                    <h3 className="text-lg font-medium text-slate-800 mb-2">Currently Healthy</h3>
                    <p className="text-sm text-slate-500">
                      I'm feeling well and want a prevention plan based on my illness patterns.
                    </p>
                  </button>
                </div>

                {/* Symptom input (for ill mode) */}
                {mode === 'ill' && (
                  <motion.div
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    className="bg-white/80 backdrop-blur-2xl rounded-[32px] shadow-[0_8px_30px_rgb(0,0,0,0.03)] border border-white p-6"
                  >
                    <label className="block text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-3">
                      Describe your symptoms
                    </label>
                    <textarea
                      value={symptoms}
                      onChange={(e) => setSymptoms(e.target.value)}
                      rows={3}
                      className="w-full px-4 py-3 bg-white/50 border border-slate-200 rounded-2xl outline-none focus:border-[#2EC4B6] focus:ring-2 focus:ring-[#2EC4B6]/20 text-slate-800 resize-none"
                      placeholder="e.g., I have a sore throat, mild fever, and body ache since 2 days..."
                    />
                  </motion.div>
                )}

                {mode && (
                  <motion.button
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    onClick={generatePlan}
                    disabled={loading || (mode === 'ill' && !symptoms.trim())}
                    className="w-full py-4 bg-gradient-to-r from-[#2EC4B6] to-[#20A498] hover:from-[#27B4A6] hover:to-[#1B9489] text-white rounded-2xl font-semibold shadow-[0_8px_20px_rgba(46,196,182,0.3)] transition-all flex items-center justify-center gap-2 disabled:opacity-60 disabled:cursor-not-allowed"
                  >
                    {loading ? (
                      <><Loader2 className="w-5 h-5 animate-spin" /> Generating your plan...</>
                    ) : (
                      <><Sparkles className="w-5 h-5" /> Generate Diet Plan</>
                    )}
                  </motion.button>
                )}
              </motion.div>
            ) : (
              /* Diet Plan Results */
              <motion.div
                key="results"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="space-y-6"
              >
                {/* Header Card */}
                <div className="rounded-[32px] p-8 relative overflow-hidden" style={{ background: 'linear-gradient(145deg, #0F3D3E 0%, #2EC4B6 100%)' }}>
                  <div className="relative z-10">
                    <div className="flex items-center gap-2 mb-3">
                      <Salad className="w-5 h-5 text-white/90" />
                      <span className="text-[11px] font-bold text-white/80 uppercase tracking-widest">
                        {plan.mode === 'ill' ? 'Healing Diet Plan' : 'Prevention Diet Plan'}
                      </span>
                    </div>
                    <h2 className="text-2xl font-semibold text-white mb-2">{plan.title}</h2>
                    <p className="text-sm text-white/80 leading-relaxed">{plan.summary}</p>
                  </div>
                </div>

                {/* Eat / Avoid */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="bg-white/80 backdrop-blur-2xl rounded-[32px] shadow-sm border border-white p-6">
                    <h3 className="text-sm font-bold text-[#22C55E] uppercase tracking-wider mb-4 flex items-center gap-2">
                      <UtensilsCrossed className="w-4 h-4" /> What to Eat
                    </h3>
                    <ul className="space-y-2">
                      {plan.eat.map((item, i) => (
                        <li key={i} className="text-sm text-slate-700 flex items-start gap-2">
                          <span className="text-[#22C55E] mt-0.5">✓</span> {item}
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="bg-white/80 backdrop-blur-2xl rounded-[32px] shadow-sm border border-white p-6">
                    <h3 className="text-sm font-bold text-[#E63946] uppercase tracking-wider mb-4 flex items-center gap-2">
                      <Ban className="w-4 h-4" /> What to Avoid
                    </h3>
                    <ul className="space-y-2">
                      {plan.avoid.map((item, i) => (
                        <li key={i} className="text-sm text-slate-700 flex items-start gap-2">
                          <span className="text-[#E63946] mt-0.5">✕</span> {item}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Kadha Recipe */}
                <div className="bg-gradient-to-br from-amber-50 to-orange-50 backdrop-blur-2xl rounded-[32px] shadow-sm border border-amber-100 p-6">
                  <h3 className="text-sm font-bold text-amber-700 uppercase tracking-wider mb-4 flex items-center gap-2">
                    <Coffee className="w-4 h-4" /> {plan.kadha_recipe.name}
                  </h3>
                  <div className="space-y-3">
                    <div>
                      <span className="text-xs font-bold text-amber-600 uppercase">Ingredients:</span>
                      <p className="text-sm text-slate-700 mt-1">{plan.kadha_recipe.ingredients.join(', ')}</p>
                    </div>
                    <div>
                      <span className="text-xs font-bold text-amber-600 uppercase">Method:</span>
                      <p className="text-sm text-slate-700 mt-1">{plan.kadha_recipe.method}</p>
                    </div>
                    <div>
                      <span className="text-xs font-bold text-amber-600 uppercase">When to drink:</span>
                      <p className="text-sm text-slate-700 mt-1">{plan.kadha_recipe.when_to_drink}</p>
                    </div>
                  </div>
                </div>

                {/* Meal Plan */}
                <div className="bg-white/80 backdrop-blur-2xl rounded-[32px] shadow-sm border border-white p-6">
                  <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                    <Salad className="w-4 h-4 text-[#2EC4B6]" /> Daily Meal Plan
                  </h3>
                  <div className="space-y-3">
                    {Object.entries(plan.meal_plan).map(([time, meal]) => (
                      <div key={time} className="flex items-start gap-4 p-3 rounded-2xl hover:bg-slate-50 transition-colors">
                        <span className="text-xs font-bold text-[#2EC4B6] uppercase tracking-wider w-32 shrink-0 mt-0.5">
                          {time.replace('_', ' ')}
                        </span>
                        <span className="text-sm text-slate-700">{meal}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Tips */}
                <div className="bg-white/80 backdrop-blur-2xl rounded-[32px] shadow-sm border border-white p-6">
                  <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                    <Leaf className="w-4 h-4 text-[#2EC4B6]" /> Additional Tips
                  </h3>
                  <ul className="space-y-2">
                    {plan.tips.map((tip, i) => (
                      <li key={i} className="text-sm text-slate-700 flex items-start gap-2">
                        <Heart className="w-3.5 h-3.5 text-[#2EC4B6] mt-0.5 shrink-0" /> {tip}
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Actions */}
                <div className="flex gap-4">
                  <button
                    onClick={() => { setPlan(null); setMode(null); setSymptoms(''); }}
                    className="flex-1 py-4 bg-white/80 border border-slate-200 text-slate-700 rounded-2xl font-semibold hover:bg-slate-50 transition-all"
                  >
                    Generate New Plan
                  </button>
                  <button
                    onClick={handleDownloadPDF}
                    className="flex-1 py-4 bg-[#0F3D3E] hover:bg-[#1A595A] text-white rounded-2xl font-semibold shadow-lg transition-all flex items-center justify-center gap-2"
                  >
                    <Download className="w-5 h-5" /> Download Plan
                  </button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>
      </main>
    </div>
  );
}
